server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

# datasource
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
      username: root
      password: 12345678
  jpa:
    database: MYSQL
    show-sql: true
  ## Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security:
  ignored: /favicon.ico,/scripts/**,/styles/**,/images/**
  sessions: ALWAYS
  oauth2:
      sso:
        loginPath: /login
      client:
        clientId: ssoclient
        clientSecret: ssosecret
        accessTokenUri: http://localhost/oauth/token
        userAuthorizationUri: http://localhost/oauth/authorize
        clientAuthenticationScheme: form
      resource:
        jwt:
          keyUri: http://localhost/oauth/token_key

securityconfig:
  logoutsuccssurl: /tosignout
  permitall: /rest/**,/bb**
  deniedpage: /deny
  urlroles: /**/new/** = admin;
            /**/edit/** = admin,editor;
            /**/delete/** = admin